version: '3.8'

services:
  # Database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: cipher_nexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  # AI Service
  ai_service:
    build:
      context: ./packages/ai
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
